
package client;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.Socket;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tu4nFPT
 */
public final class Client extends javax.swing.JFrame {

    /**
     * Creates new form Client
     */
    private final int PORT = 1234;
    private Socket socket;
    private BufferedReader in;
    private PrintStream out;

    private String ipAddress;
    private String userName;
    
    public Client() {
        initComponents();
        this.setSize(565, 535);
        this.setLocationRelativeTo(null);
        txtChat.requestFocus();
        txtChat.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!txtChat.getText().equals("")) {
                    out.println(userName + ": " + txtChat.getText());
                    txtChat.setText("");
                }
            }
        });
        while(true){
            try {
                ipAddress = getServerAddress();               
                socket = new Socket(ipAddress, PORT);
                out = new PrintStream(socket.getOutputStream(), true);
                in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                userName = getUserName();
                new ClientRead(this, userName, in).start();
                break;
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Can't connect to Server !");
            }
        }
    }

    public String getServerAddress() {
        return JOptionPane.showInputDialog(this, "Enter IP Adress of Server: ");
    }

    public String getUserName() {
        String name = "";
        do {
            name = JOptionPane.showInputDialog(this, "Enter Your Name: ");
        } while (name.equals(""));
        return name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn = new javax.swing.JPanel();
        txtChat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtScreen = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn.setLayout(null);

        txtChat.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtChat.setForeground(new java.awt.Color(0, 0, 255));
        pn.add(txtChat);
        txtChat.setBounds(20, 440, 510, 40);

        txtScreen.setEditable(false);
        txtScreen.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtScreen.setForeground(new java.awt.Color(51, 51, 255));
        jScrollPane1.setViewportView(txtScreen);

        pn.add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 510, 400);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background.png"))); // NOI18N
        pn.add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn;
    private javax.swing.JTextField txtChat;
    public javax.swing.JTextPane txtScreen;
    // End of variables declaration//GEN-END:variables
}
